# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Update and Publish firebaseui-id

on:
  workflow_run: 
    workflows: [build]
    types: [requested]
  push: 
    branches:
      - master
      - main
  schedule:
   - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      - run: git config --global user.email "actions@github.com"
      - run: git config --global user.name "Github"
      - run: |
              if [[ `npm info firebaseui version` != `npm info firebaseui-id version` ]]
              then 
                git clone --depth=1 --branch v`npm info firebaseui version` https://github.com/firebase/firebaseui-web.git firebaseui-id
                node ./prepare.js
                cp README.md firebaseui-id/
              fi
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: "Install, build and publish"
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
        run: |
              if [[ -d firebaseui-id ]]
              then
                cd firebaseui-id
                npm ci
                npm run build
                npm run build build-js-id && npm run build build-esm-id && npm run build build-npm-id
                npm publish
              fi
